/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  ai_chat: () => import("@/views/ai/chat/index.vue"),
  alarm: () => import("@/views/alarm/index.vue"),
  fleet: () => import("@/views/fleet/index.vue"),
  geofence: () => import("@/views/geofence/index.vue"),
  home: () => import("@/views/home/index.vue"),
  media: () => import("@/views/media/index.vue"),
  monitor: () => import("@/views/monitor/index.vue"),
  ota: () => import("@/views/ota/index.vue"),
  recording: () => import("@/views/recording/index.vue"),
  register: () => import("@/views/register/index.vue"),
  report: () => import("@/views/report/index.vue"),
  rule: () => import("@/views/rule/index.vue"),
  system_audit: () => import("@/views/system/audit/index.vue"),
  system_config: () => import("@/views/system/config/index.vue"),
  system_department: () => import("@/views/system/department/index.vue"),
  system_plan: () => import("@/views/system/plan/index.vue"),
  system_position: () => import("@/views/system/position/index.vue"),
  system_profile: () => import("@/views/system/profile/index.vue"),
  system_registration: () => import("@/views/system/registration/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_tenant: () => import("@/views/system/tenant/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  track: () => import("@/views/track/index.vue"),
  vehicle: () => import("@/views/vehicle/index.vue"),
};
