/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'alarm',
    path: '/alarm',
    component: 'layout.base$view.alarm',
    meta: {
      title: 'alarm',
      i18nKey: 'route.alarm',
      icon: 'mdi:alert-outline',
      order: 3
    }
  },
  {
    name: 'fleet',
    path: '/fleet',
    component: 'layout.base$view.fleet',
    meta: {
      title: 'fleet',
      i18nKey: 'route.fleet',
      icon: 'mdi:garage-variant',
      order: 6
    }
  },
  {
    name: 'geofence',
    path: '/geofence',
    component: 'layout.base$view.geofence',
    meta: {
      title: 'geofence',
      i18nKey: 'route.geofence',
      icon: 'mdi:vector-circle',
      order: 4
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base$view.monitor',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor',
      icon: 'mdi:map-marker-radius',
      order: 2
    }
  },
  {
    name: 'register',
    path: '/register',
    component: 'layout.blank$view.register',
    meta: {
      title: 'register',
      i18nKey: 'route.register',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'mdi:cog-outline',
      order: 90
    },
    children: [
      {
        name: 'system_audit',
        path: '/system/audit',
        component: 'view.system_audit',
        meta: {
          title: '审计日志',
          i18nKey: 'route.system_audit',
          icon: 'mdi:text-box-search-outline',
          permissions: ['system:audit:view'],
          order: 9
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: '租户配置',
          i18nKey: 'route.system_config',
          icon: 'mdi:tune',
          permissions: ['system:config:view', 'platform:config:manage'],
          order: 8
        }
      },
      {
        name: 'system_department',
        path: '/system/department',
        component: 'view.system_department',
        meta: {
          title: '部门管理',
          i18nKey: 'route.system_department',
          icon: 'mdi:file-tree-outline',
          permissions: ['system:dept:list'],
          order: 3
        }
      },
      {
        name: 'system_plan',
        path: '/system/plan',
        component: 'view.system_plan',
        meta: {
          title: '套餐与续费',
          i18nKey: 'route.system_plan',
          icon: 'mdi:package-variant-closed',
          permissions: ['platform:plan:manage'],
          order: 6
        }
      },
      {
        name: 'system_position',
        path: '/system/position',
        component: 'view.system_position',
        meta: {
          title: '岗位管理',
          i18nKey: 'route.system_position',
          icon: 'mdi:badge-account-outline',
          permissions: ['system:position:list'],
          order: 4
        }
      },
      {
        name: 'system_profile',
        path: '/system/profile',
        component: 'view.system_profile',
        meta: {
          title: '个人中心',
          i18nKey: 'route.system_profile',
          icon: 'mdi:account-cog-outline',
          order: 10
        }
      },
      {
        name: 'system_registration',
        path: '/system/registration',
        component: 'view.system_registration',
        meta: {
          title: '注册审批',
          i18nKey: 'route.system_registration',
          icon: 'mdi:clipboard-check-outline',
          permissions: ['platform:registration:review'],
          order: 7
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: '角色管理',
          i18nKey: 'route.system_role',
          icon: 'mdi:shield-account-outline',
          permissions: ['system:role:list'],
          order: 2
        }
      },
      {
        name: 'system_tenant',
        path: '/system/tenant',
        component: 'view.system_tenant',
        meta: {
          title: '租户管理',
          i18nKey: 'route.system_tenant',
          icon: 'mdi:domain',
          permissions: ['platform:tenant:manage'],
          order: 5
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: '用户管理',
          i18nKey: 'route.system_user',
          icon: 'mdi:account-group-outline',
          permissions: ['system:account:list'],
          order: 1
        }
      }
    ]
  },
  {
    name: 'track',
    path: '/track',
    component: 'layout.base$view.track',
    meta: {
      title: 'track',
      i18nKey: 'route.track',
      icon: 'mdi:map-marker-path',
      order: 5
    }
  },
  {
    name: 'vehicle',
    path: '/vehicle',
    component: 'layout.base$view.vehicle',
    meta: {
      title: 'vehicle',
      i18nKey: 'route.vehicle',
      icon: 'mdi:car-multiple',
      order: 7
    }
  }
];
