/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'alarm',
    path: '/alarm',
    component: 'layout.base$view.alarm',
    meta: {
      title: 'alarm',
      i18nKey: 'route.alarm',
      icon: 'mdi:alert-outline',
      order: 3
    }
  },
  {
    name: 'fleet',
    path: '/fleet',
    component: 'layout.base$view.fleet',
    meta: {
      title: 'fleet',
      i18nKey: 'route.fleet',
      icon: 'mdi:garage-variant',
      order: 6
    }
  },
  {
    name: 'geofence',
    path: '/geofence',
    component: 'layout.base$view.geofence',
    meta: {
      title: 'geofence',
      i18nKey: 'route.geofence',
      icon: 'mdi:vector-circle',
      order: 4
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base$view.monitor',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor',
      icon: 'mdi:map-marker-radius',
      order: 2
    }
  },
  {
    name: 'track',
    path: '/track',
    component: 'layout.base$view.track',
    meta: {
      title: 'track',
      i18nKey: 'route.track',
      icon: 'mdi:map-marker-path',
      order: 5
    }
  },
  {
    name: 'vehicle',
    path: '/vehicle',
    component: 'layout.base$view.vehicle',
    meta: {
      title: 'vehicle',
      i18nKey: 'route.vehicle',
      icon: 'mdi:car-multiple',
      order: 7
    }
  }
];
